sudo: required
services:
   - docker

before_install:
   - docker build -t shankar0043/docker-react -f Dockerfile.dev .

script:
   - docker run -e CI=true shankar0043/docker-react npm run test

deploy:
   provider: azure_web_apps
   verbose: true
   username: $User_Name
   password: $Password
   site: reactapplication1
   on:
      branch: master
